# this API specification is draft and subject to change.
openapi: "3.0.2"
info:
  title: CVE Services API
  description: The CVE services API which supports automation tooling for the CVE Project.
  version: 0.1.0
  contact:
    "name": "CVE Services API"
    "url": http://cve.mitre.org/api
    "email": placeholder-cve-services-api@mitre.org
  license:
    name: Creative Commons Zero v1.0 Universal
    url: https://creativecommons.org/publicdomain/zero/1.0/legalcode
  termsOfService: http://cve.mitre.org/api/terms
# The following is notional
servers:
  - url: https://api-dev.cve.org/v1
    description: Development and testing server
  - url: https://api.cve.mitre.org/v1
    description: Production server
components:
  parameters:
    cve-id-path:
      name: cve-id
      in: path
      description: The CVE ID for which the record is being submitted
      required: true
      schema:
        # CVE ID format
        type: string
        pattern: 'CVE-\d{4}-\d+'
    api-entity-header:
      name: CVE-API-CNA
      description: >
        The shortname for the entity (e.g., CNA, ADP) that is authenticated or requesting authentication. \[TODO:: Is there a pattern for the format?\]
      in: header
      required: true
      schema:
        type: string
    api-user-header:
      name: CVE-API-SUBMITTER
      description: >
        The username for the account that is making the request.
      in: header
      required: true
      schema:
        type: string
    api-secret-header:
      name: CVE-API-SECRET
      description: >
        The User's secret. \[TODO:: Is there a pattern for the format?\]
      in: header
      required: true
      schema:
        type: string
paths:
  # CVE ID Reservation service
  /cve-id:
    get:
      summary: Retrieves all CVE IDs entity owns.
      parameters:
        - in: query
        name: state
        schema:
          type: string
        description: "Filter by CVE state: RESERVED, PUBLIC, or REJECT"
        - in: query
        name: cve_id_year
        schema:
          type: integer
        description: "Filter by the year in the CVE ID (YYYY)"
        - in: query
        name: time_created.lt
        schema:
          type: timestamp
        description: "Get all CVE IDs created (reserved) before timestamp"
        - in: query
        name: time_created.gt
        schema:
          type: timestamp
        description: "Get all CVE IDs created (reserved) after timestamp"
    post:
      summary: Reserves IDs for the entity.
  /cve-id/{cve-id}:
    parameters:
      - "$ref": "#/components/parameters/cve-id-path"
    get:
      summary: Retrieves a CVE ID by ID, can be a CVE the entity doesn't own if in a PUBLIC or REJECT state.
      operationId: getCVEIdById
      responses:
        200:
          description: >
            The requested CVE ID is returned.
          content:
            application/json:
              schema:
                type: object
                # add CVE-ID JSON format
        401:
          description: Not Authenticated
        404:
            description: Not Found
    post:
      summary: Endpoint for Admin purposes to change state and ownership of the CVE ID.
      operationId: submitCVEIdById
      parameters:
        - "$ref": "#/components/parameters/api-entity-header"
        - "$ref": "#/components/parameters/api-secret-header"
        - "$ref": "#/components/parameters/api-user-header"
        - in: query
        name: state
        schema:
          type: string
        description: "Change state of CVE ID to either PUBLIC or REJECT"
        - in: query
        name: cna
        schema:
          type: string
        description: "Change owning CNA of CVE ID to new CNA (shortname)"
      responses:
        200:
          description: Success
        400:
          description: Bad Request
        401:
          description: Not Authenticated
        403:
          description: Forbidden
        404:
          description: Not Found
