version: '3'

services:
  docdb:
    image: mongo
    container_name: mongo
    env_file: .docker-env
    ports:
      - "27017:27017"
    networks:
      - cve-services

  cveawg:
    container_name: cveawg
    user: node # The user to run as in the container
    build:
      context: ../
      dockerfile: docker/Dockerfile
    depends_on:
      - docdb
    env_file: .docker-env
    ports:
      - "3000:3000"
    networks:
      - cve-services

networks:
  cve-services:
